export const speed_lines  = {
        canvasWidth: 1920,
        canvasHeight: 1080,
        centerX: 0.5,
        centerY: 0.5,
        innerRadius: 0.2,
        outerRadius: 0.8,
        innerRadiusRandomization: 0.5,
        outerRadiusRandomization: 0.1,
        startAngle: 0,
        endAngle: 360,
        rayLife: 20,
        numCycles: 6,
        numRays: 100,
        rayColors: [[100,100,100]],
        blendMode: 'normal',
        thickness: 0.05,
        feather: 0.1,
        amplitude: 0.04,
        frequency: 0.2,
        pattern: 'sine',
        perspectiveSkew: 0.5,
        includeFadeInOut: true,
        phaseRandomization: 0.1,
        backgroundColor: [0, 0, 0],
        rayLength: 0.5,
        rayLengthRandomization: 0.4,
        thicknessRandomization: 0.0,

        strokeCap: 0.5,
    }

export const warp_speed  = {
        canvasWidth: 1920,
        canvasHeight: 1080,
        centerX: 0.5,
        centerY: 0.5,
        innerRadius: 0.2,
        outerRadius: 1.0,
        innerRadiusRandomization: 0.9,
        outerRadiusRandomization: 0.1,
        startAngle: 0,
        endAngle: 360,
        rayLife: 50,
        numCycles: 3,
        numRays: 1500,
        rayColors: [[150,50,250],[0,30,180],[150,200,250]],
        blendMode: 'additive',
        thickness: 0.06,
        feather: 0.8,
        amplitude: 0.0,
        frequency: 0.0,
        pattern: 'sine',
        perspectiveSkew: 0.9,
        includeFadeInOut: false,
        phaseRandomization: 0.1,
        backgroundColor: [0, 0, 66],
        rayLength: 0.5,
        rayLengthRandomization: 0.5,
        thicknessRandomization: 0.5,
        strokeCap: 0.1,
    }

    export const star_shimmer  = {
        canvasWidth: 1920,
        canvasHeight: 1080,
        centerX: 0.5,
        centerY: 0.5,
        innerRadius: 0.0,
        outerRadius: 0.05,
        innerRadiusRandomization: 0.9,
        outerRadiusRandomization: 1,
        startAngle: 0,
        endAngle: 360,
        rayLife: 100,
        numCycles: 3,
        numRays: 100,
        rayColors: [[250,60,240],[70,30,180],[0,250,250],[255,255,255]],
        blendMode: 'additive',
        thickness: 0.1,
        feather: 0.8,
        amplitude: 0.0,
        frequency: 0.0,
        pattern: 'sine',
        perspectiveSkew: 1,
        includeFadeInOut: false,
        phaseRandomization: 0.1,
        backgroundColor: [30, 0, 66],
        rayLength: 0.8,
        rayLengthRandomization: 0.1,
        thicknessRandomization: 0.1,
        strokeCap: 0.08,
    }

    export const star_field  = {
        canvasWidth: 1920,
        canvasHeight: 1080,
        centerX: 0.5,
        centerY: 0.5,
        innerRadius: 0.5,
        outerRadius: 1.0,
        innerRadiusRandomization: 1.,
        outerRadiusRandomization: 0.1,
        startAngle: 0,
        endAngle: 360,
        rayLife: 150,
        numCycles: 3,
        numRays: 400,
        rayColors: [[255,200,150],[250,0,0]],
        blendMode: 'additive',
        thickness: 0.03,
        feather: 1.0,
        amplitude: 0.2,
        frequency: 0.2,
        pattern: 'sine',
        perspectiveSkew: 0.3,
        includeFadeInOut: false,
        phaseRandomization: 0.1,
        backgroundColor: [20, 0, 0],
        rayLength: 0.04,
        rayLengthRandomization: 0.0,
        thicknessRandomization: .8,

        strokeCap: 0.1,
    }

        export const spaghetti  = {
        canvasWidth: 1920,
        canvasHeight: 1080,
        centerX: 0.5,
        centerY: 0.5,
        innerRadius: 0.05,
        outerRadius: 0.7,
        innerRadiusRandomization: 1.0,
        outerRadiusRandomization: 0.,
        startAngle: 0,
        endAngle: 360,
        rayLife: 150,
        numCycles: 3,
        numRays: 100,
        rayColors: [[255,160,0],[255,180,90],[230,130,50]],
        blendMode: 'normal',
        thickness: 0.1,
        feather: .1,
        amplitude: 0.15,
        frequency: 0.2,
        pattern: 'sine',
        perspectiveSkew: 0.7,
        includeFadeInOut: false,
        phaseRandomization: 0.1,
        backgroundColor: [200, 0, 0],
        rayLength: 1.,
        rayLengthRandomization: 0.3,
        thicknessRandomization: .0,

        strokeCap: 0.8,
    }